services:
  # db:
  #   image: postgres:13
  #   environment:
  #     - POSTGRES_PASSWORD=${DB_PASS}
  #     - POSTGRES_USER=${DB_USER}
  #     - POSTGRES_DB=${DB_NAME}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - db-data:/var/lib/postgresql/data

  app:
    build: .
    # depends_on:
    #   - db
    # links:
    #   - db
    ports:
      - "8080:8081"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    volumes:
      - ./migrations:/app/migrations

volumes:
  db-data:
    name: db-data