version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cloneai
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    links:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=cloneai
      - DB_USER=postgres
      - DB_PASS=password
    volumes:
      - ./migrations:/app/migrations

volumes:
  db-data:
    name: db-data